ViewHolder memory leak fix
Having a class variable like val parent: ViewGroup would cause a memory leak and crash in a recyclerView like:
illegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.recyclerview.widget.RecyclerView

Above exception will happens when you have animations like MotionLayout or just simply changing recycler's size dynamically (hidding other sibling UI element with an user action).